// Books data
export const booksData = {
    popular: [
      {
        id: 1,
        title: "Adventures of Sherlock Holmes",
        author: "Arthur Conan Doyle",
        cover: "/Book_Images/The Adventure of Sherlock Holmes.png",
        description: "A classic detective story set in Victorian London, featuring Sherlock Holmes and his friend Dr. Watson.",
        rating: 4.5,
        pages: 400,
        publisher: "Harper Collins",
        published: "1894",
        language: "English",
      },
      {
        id: 2,
        title: "The Alchemist",
        author: "Paulo Coelho",
        cover: "/Book_Images/The Alchemist.png",
        description: "A fable about a young shepherd who sets out on a journey to fulfill his dream of finding a way to communicate with animals.", 
        rating: 4.7,
        pages: 200,
        publisher: "Harper Collins",
        published: "1988",
        language: "English",
      },
      {
        id: 3,
        title: "Frankenstein",
        author: "Mary Shelley",
        cover: "/Book_Images/Frankenstein.png",
        description: "A classic Gothic novel about a scientist who creates a monster and the consequences that follow the creation of a monster.",
        rating: 4.3,
        pages: 300,
        publisher: "Penguin Books",
        published: "1818",
        language: "English",
      },
      {
        id: 4,
        title: "The Color Purple",
        author: "Alice Walker",
        cover: "/Book_Images/The Color Purple.png",
        description: "A novel about the lives of African American women in the rural South during the early 1930s.",
        rating: 4.6,
        pages: 400,
        publisher: "Harper Collins",
        published: "1982",
        language: "English",
      },
      {
        id: 5,
        title: "All Quiet on the Western Front",
        author: "Erich Maria Remarque",
        cover: "/Book_Images/western-front.png",
        description: "A classic novel about a young German soldier who experiences the horrors of World War I.",
        rating: 4.4,
        pages: 300,
        publisher: "Penguin Books",
        published: "1929",
        language: "English",
      },
    ],
    fiction: [
      { id:6, title: "1984", author: "George Orwell", cover: "/Book_Images/1984.png", description: "A dystopian novel about a totalitarian regime and its effects on the lives of its citizens.", rating:4.4, pages: 200 },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        cover: "/Book_Images/Mocking-bird.png",
        description: "A classic novel about a young girl who learns about racial injustice and the importance of empathy and justice.",
        rating: 4.7,
        pages: 300,
      },
      {
        id: 8,
        title: "All the light we cannot see",
        author: "Anthony Doerr",
        cover: "/Book_Images/All the light we cannot see.png",
        description: "A novel about a young girl who discovers the truth about her family's past and the consequences of her actions." ,
        rating: 4.5, 
        pages: 300,
      },
      {
        id: 9,
        title: "Animal Farm",
        author: "George Orwell",
        cover: "/Book_Images/Animal Farm.png",
        description: "A dystopian novel about a group of animals who overthrow their human oppressors and establish a new society.",
        rating: 4.4,
        pages: 200,
      },
      {
        id: 10,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        cover: "/Book_Images/Handmaid tail.png",
        description: "A novel about a young man who discovers his true identity and the importance of self-discovery and self-love.",
        rating: 4.5,
        pages: 200,
      },
    ],
    nonFiction: [
      {
        id: 11,
        title: "Sapiens",
        author: "Yuval Noah Harari",
        cover: "/Book_Images/Sapiens.png",
        description: "A book that explores the history of humanity and the impact of technology on our lives.",
        rating: 4.7,
        pages: 400,
      },
      {
        id: 12,
        title: "Educated",
        author: "Tara Westover",
        cover: "/Book_Images/Educated.png",
        description: "A memoir about the author's experiences growing up in a poor family and her journey to become a successful writer.",
        rating: 4.6,
        pages: 400,
      },
      {
        id: 13,
        title: "Becoming",
        author: "Michelle Obama",
        cover: "/Book_Images/Becoming.png",
        description: "A memoir about the author's experiences growing up in a poor family and her journey to become a successful writer.",
        rating: 4.5,
        pages: 400,
      },
      {
        id: 14,
        title: "Eat that Frog",
        author: "Brian Tracy",
        cover: "/Book_Images/Eat that Frog.png",
        description: "A book that provides practical advice on how to succeed in life and achieve your goals.",
        rating: 4.8,
        pages: 200,
      },
      {
        id: 15,
        title: "How to win Friends and Influence people",
        author: "Dale Carnegie",
        cover: "/Book_Images/Influence-people.png",
        description: "A book that provides practical advice on how to succeed in life and achieve your goals.",
        rating: 4.9,
        pages: 200,
      },
    ],
  };
// export const genre={
//     genres:[
//         "popular","friction","nonfriction","Self-help","computer",""
//     ]

// }